[env]
term = "xterm-256color"

# Colors (acme) - modified.
# Default colors
[colors.primary]
background =  '#ffffea'
foreground =  '#000000'

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[font]
size = 16.0

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Inconsolata"
style = "Italic"

[font.normal]
family = "Inconsolata"
style = "Regular"

[font.offset]
x = 0
y = 5

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
